<?php
if( function_exists('acf_add_local_field_group') ):

    function addMenuField($key) {

    }

    acf_add_local_field_group(array(
        'key' => 'group_5f5b28ba1a424',
        'title' => 'Content',
        'fields' => array(
            array(
                'key' => 'field_5f5b28bd77ec7',
                'label' => 'Content',
                'name' => 'content',
                'type' => 'flexible_content',
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layouts' => array(
                    'layout_5f5b28c2cc6cdda' => array(
                        'key' => 'layouat_5f5ddb28c2cc6ca',
                        'name' => 'blue_booble_image_text',
                        'label' => 'Tekst i blå bobel og billede',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'fielad_5f5b298977eca',
                                'label' => 'Tekst',
                                'name' => 'text',
                                'type' => 'textarea',
                                'maxlength' => '100',
                                'required' => 1,
                            ),
                            array(
                                'key' => 'field_g5f5b299377ecb',
                                'label' => 'Billede',
                                'name' => 'picture',
                                'type' => 'image',
                                'required' => 1,
                            )
                        ),
                    ),
                    'layout_5f5b28c2cc6ca' => array(
                        'key' => 'layout_5f5b28c2cc6ca',
                        'name' => 'picture_and_text',
                        'label' => 'Billede og tekst',
                        'display' => 'block',
                        'sub_fields' => array(
                            addMenuField('field_5f5def6b7147f'),
                            array(
                                'key' => 'field_5f5b295577ec8',
                                'label' => 'Overskrift',
                                'name' => 'headline',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 1,
                            ),
                            array(
                                'key' => 'field_5f5b298977eca',
                                'label' => 'Tekst',
                                'name' => 'text',
                                'type' => 'wysiwyg',
                                'required' => 1,
                            ),
                            array(
                                'key' => 'field_5f5b299377ecb',
                                'label' => 'Billede',
                                'name' => 'picture',
                                'type' => 'image',
                                'required' => 1,
                            )
                        ),
                    ),
                    'layout_5f5b2c694a599' => array(
                        'key' => 'layout_5f5b2c694a599',
                        'name' => 'hero',
                        'label' => 'Hero',
                        'display' => 'block',
                        'sub_fields' => array(
                            addMenuField('field_5f5defbe09d55'),
                            array(
                                'key' => 'field_5f5b37e0975d0',
                                'label' => 'Overskrift',
                                'name' => 'headline',
                                'type' => 'text',
                                'required' => 1,
                            ),
                            array(
                                'key' => 'field_5f6aa1bd079b209',
                                'label' => 'Ikon kasser',
                                'name' => 'icon_boxes',
                                'type' => 'repeater',
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'table',
                                'button_label' => 'Ny kasse',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_ee5fa61bd179b20a',
                                        'label' => 'Ikon',
                                        'name' => 'picture',
                                        'type' => 'image',
                                        'instructions' => 'Vi anbefaler SVG ikoner. En god kilde til dem er her: https://www.iconfinder.com/',
                                        'required' => 1,
                                        'return_format' => 'array',
                                        'preview_size' => 'medium',
                                        'library' => 'all',
                                    ),
                                    array(
                                        'key' => 'field_5fkf61bd2d9b20c',
                                        'label' => 'Tekst',
                                        'name' => 'text',
                                        'type' => 'textarea',
                                        'tabs' => 'visual',
                                        'toolbar' => 'basic',
                                        'media_upload' => 1,
                                        'delay' => 0,
                                    ),
                                ),
                            ),
                            array(
                                'key' => 'field_5f5b37f4975d2',
                                'label' => 'Billede',
                                'name' => 'picture',
                                'type' => 'file',
                                'required' => 1,
                                'return_format' => 'array',
                                'library' => 'all',
                                'mime_types' => 'png,jpg,jpeg',
                            ),
                            array(
                                'key' => 'hero_media_handheld',
                                'label' => 'Billede / Video - mobil / tablet',
                                'name' => 'hero_media_handheld',
                                'instructions' => 'Efterlad dette felt tomt hvis du ønsker at bruge samme billede / video som du gør på desktop',
                                'type' => 'file',
                                'return_format' => 'array',
                                'library' => 'all',
                                'mime_types' => 'mp4,png,jpg,jpeg',
                            ),
                        ),
                    ),
                    'layout_5f5b3cd0f12bb' => array(
                        'key' => 'layout_5f5b3cd0f12bb',
                        'name' => 'contact_form',
                        'label' => 'Kontakt form',
                        'display' => 'block',
                        'sub_fields' => array(
                            addMenuField('field_5f5defe209d56'),
                            array(
                                'key' => 'field_5f5b3cd9f12bc',
                                'label' => 'Vælg kontakt form',
                                'name' => 'contact_form',
                                'type' => 'relationship',
                                'required' => 1,
                                'post_type' => array(
                                    0 => 'wpcf7_contact_form',
                                ),
                                'taxonomy' => '',
                                'filters' => array(
                                    0 => 'search',
                                    1 => 'post_type',
                                    2 => 'taxonomy',
                                ),
                                'elements' => '',
                                'min' => 1,
                                'max' => 1,
                                'return_format' => 'id',
                            ),
                            array(
                                'key' => 'field_5f5b3d0ef12bd',
                                'label' => 'Overskrift',
                                'name' => 'headline',
                                'type' => 'text',
                            ),
                            array(
                                'key' => 'field_5f5bd37f4975d2',
                                'label' => 'Billede',
                                'name' => 'picture',
                                'type' => 'file',
                                'required' => 1,
                                'return_format' => 'array',
                                'library' => 'all',
                                'mime_types' => 'svg,png,jpg,jpeg',
                            ),
                            array(
                                'key' => 'field_5f5b3d0ef12adsdbd',
                                'label' => 'Overskrift i billede',
                                'name' => 'headline_in_pic',
                                'type' => 'text',
                            ),
                            array(
                                'key' => 'field_5fasd5b3d1af12be',
                                'label' => 'Tekst i billede',
                                'name' => 'text',
                                'type' => 'textarea',
                                'default_value' => '',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                                'delay' => 0,
                            ),
                        ),
                    ),
                    'layout_5f5b54361ee4a' => array(
                        'key' => 'layout_5f5b54361ee4a',
                        'name' => 'blog',
                        'label' => 'Blog',
                        'display' => 'block',
                        'sub_fields' => array(
                            addMenuField('field_5f5deff809d57'),
                            array(
                                'key' => 'field_5f5e08c384c9b',
                                'label' => 'Blog indlæg',
                                'name' => 'blog_items',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'table',
                                'button_label' => 'Nyt blog indlæg',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5f5b543b1ee4b',
                                        'label' => 'Blog indlæg',
                                        'name' => 'blog_link',
                                        'type' => 'relationship',
                                        'required' => 1,
                                        'post_type' => array(
                                            0 => 'post',
                                        ),
                                        'taxonomy' => '',
                                        'filters' => array(
                                            0 => 'search',
                                            1 => 'post_type',
                                            2 => 'taxonomy',
                                        ),
                                        'elements' => '',
                                        'min' => 1,
                                        'max' => 1,
                                        'return_format' => 'object',
                                    ),
                                    array(
                                        'key' => 'field_5f5e08f284c9c',
                                        'label' => 'Billede',
                                        'name' => 'picture',
                                        'type' => 'image',
                                        'return_format' => 'array',
                                        'preview_size' => 'medium',
                                        'library' => 'all',
                                    ),
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_5f5b71aa39382' => array(
                        'key' => 'layout_5f5b71aa39382',
                        'name' => 'spacer',
                        'label' => 'Luft',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5f5b71b239383',
                                'label' => 'PX luft til top',
                                'name' => 'space_top',
                                'type' => 'number',
                            ),
                            array(
                                'key' => 'field_5f5b71dd39384',
                                'label' => 'PX luft til bund',
                                'name' => 'space_bottom',
                                'type' => 'number',
                            ),
                        ),
                    ),
                    'layout_5f5dfce941db7' => array(
                        'key' => 'layout_5f5dfce941db7',
                        'name' => 'divider',
                        'label' => 'Adskiller linje',
                        'display' => 'block',
                        'sub_fields' => array(
                        ),
                    ),
                    'layout_5f5dfea8bf1cf' => array(
                        'key' => 'layout_5f5dfea8bf1cf',
                        'name' => 'headline',
                        'label' => 'Overskrift',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5f5dfeafbf1d0',
                                'label' => 'Overskrift',
                                'name' => 'headline',
                                'type' => 'text',
                                'required' => 1,
                            ),

                            array(
                                'key' => 'field_5ddf5b3ab51a36e',
                                'label' => 'Placering',
                                'name' => 'align',
                                'type' => 'radio',
                                'required' => 1,
                                'choices' => array(
                                    'left' => 'Venstre',
                                    'center' => 'center',
                                    'right' => 'Højre',
                                ),
                                'allow_null' => 0,
                                'other_choice' => 0,
                                'default_value' => '',
                                'layout' => 'vertical',
                                'return_format' => 'value',
                                'save_other_choice' => 0,
                            ),
                        ),
                    ),
                    'layout_5f5dfeb8bf1d1' => array(
                        'key' => 'layout_5f5dfeb8bf1d1',
                        'name' => 'text',
                        'label' => 'Tekst block',
                        'display' => 'block',
                        'sub_fields' => array(
                            addMenuField('field_5f5dff092da01'),
                            array(
                                'key' => 'field_5f5dfec8bf1d2',
                                'label' => 'Tekst',
                                'name' => 'text',
                                'type' => 'wysiwyg',
                                'required' => 1,
                                'default_value' => '',
                                'tabs' => 'all',
                                'toolbar' => 'basic',
                                'media_upload' => 1,
                                'delay' => 0,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_5f61abce29b208' => array(
                        'key' => 'layout_5df61bce29b208',
                        'name' => 'services_boxes',
                        'label' => 'Service kasser',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5f5dfeafpbf1d0',
                                'label' => 'Overskrift',
                                'name' => 'headline',
                                'type' => 'text',
                                'required' => 1,
                            ),
                            array(
                                'key' => 'field_5f6a1bd079b20dd9',
                                'label' => 'Kasser',
                                'name' => 'boxes',
                                'type' => 'repeater',
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'table',
                                'button_label' => 'Ny kasse',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5f61bd1f79b20a',
                                        'label' => 'Ikon',
                                        'name' => 'picture',
                                        'type' => 'image',
                                        'instructions' => 'Vi anbefaler SVG ikoner. En god kilde til dem er her: https://www.iconfinder.com/',
                                        'required' => 1,
                                        'return_format' => 'array',
                                        'preview_size' => 'medium',
                                        'library' => 'all',
                                    ),
                                    array(
                                        'key' => 'field_5fd61bd249b20b',
                                        'label' => 'Overskrift',
                                        'name' => 'headline',
                                        'type' => 'text',
                                        'required' => 1,
                                    ),
                                    array(
                                        'key' => 'field_5f6a1bd2d9b20c',
                                        'label' => 'Tekst',
                                        'name' => 'text',
                                        'type' => 'wysiwyg',
                                        'tabs' => 'visual',
                                        'toolbar' => 'basic',
                                        'media_upload' => 1,
                                        'delay' => 0,
                                    ),
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_5f61bce29b208' => array(
                        'key' => 'layout_5f61bce29b208',
                        'name' => 'feature_boxes',
                        'label' => 'Kasser med Ikon, overskrift og tekst',
                        'display' => 'block',
                        'sub_fields' => array(
                            addMenuField('field_5f61be1d2c4ab'),
                            array(
                                'key' => 'row_count',
                                'label' => 'Hvor mange kasser pr række?',
                                'name' => 'row_count',
                                'type' => 'number',
                                'instructions' => 'Her bestemmer du hvor mange kasser der maksimalt må vises på en række.',
                                'default_value' => 3,
                                'required' => 1,
                            ),
                            array(
                                'key' => 'field_5f61bd079b209',
                                'label' => 'Kasser',
                                'name' => 'boxes',
                                'type' => 'repeater',
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'table',
                                'button_label' => 'Ny kasse',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5f61bd179b20a',
                                        'label' => 'Ikon',
                                        'name' => 'picture',
                                        'type' => 'image',
                                        'instructions' => 'Vi anbefaler SVG ikoner. En god kilde til dem er her: https://www.iconfinder.com/',
                                        'required' => 1,
                                        'return_format' => 'array',
                                        'preview_size' => 'medium',
                                        'library' => 'all',
                                    ),
                                    array(
                                        'key' => 'field_5f61bd249b20b',
                                        'label' => 'Overskrift',
                                        'name' => 'headline',
                                        'type' => 'text',
                                        'required' => 1,
                                    ),
                                    array(
                                        'key' => 'field_5f61bd2d9b20c',
                                        'label' => 'Tekst',
                                        'name' => 'text',
                                        'type' => 'wysiwyg',
                                        'tabs' => 'visual',
                                        'toolbar' => 'basic',
                                        'media_upload' => 1,
                                        'delay' => 0,
                                    ),
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                ),
                'button_label' => 'Add Row',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                )
            ),
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                )
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

endif;